# Site settings
title: Dokumentacja
email: andrzej.max.marcinkowski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Dokumentacja oprogramowania tworzonego na potrzeby Wojew√≥dzkiego Szpitala Zespolonego im. L. Perzyny w Kaliszu.
baseurl: "http://amarcinkowski.github.io" # the subpath of your site, e.g. /blog/
url: "http://amarcinkowski.github.io" # the base hostname & protocol for your site
github_username:  amarcinkowski
# Build settings
markdown: kramdown
